# apiVersion: v1
# kind: Namespace
# metadata:
#   name: mern-app

---
apiVersion: v1
kind: Secret
metadata:
  name: documentdb-credentials
  namespace: mern-app
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: "REPLACE_WITH_DOCUMENTDB_PASSWORD"
  MONGO_URI: "REPLACE_WITH_PRIMARY_DOCUMENTDB_MONGO_URI"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: mern-app
type: Opaque
stringData:
  JWT_SECRET: dGhpcyBpcyBhIHZlcnkgbG9uZyByYW5kb20gc2VjcmV0IGtleSBmb3IgSldUIHRva2VuaXphdGlvbiB0aGF0IG11c3QgYmUgYXQgbGVhc3QgNjQgY2hhcmFjdGVycw==
  JWT_EXPIRES_IN: "7d"
  MONGO_URI: "REPLACE_WITH_PRIMARY_DOCUMENTDB_MONGO_URI"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mern-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  CORS_ORIGINS: "http://localhost,http://frontend"
