apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - 01-namespace-secrets.yaml
  - 02-mongodb.yaml
  - ingress.yaml

  - api-gateway/deployment.yaml
  - api-gateway/service.yaml

  - auth-service/deployment.yaml
  - auth-service/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - tasks-service/deployment.yaml
  - tasks-service/service.yaml