apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: tasks-service
spec:
  type: ClusterIP
  selector:
    app: tasks-service
  ports:
    - port: 5002
      targetPort: 5002
